sensu/sensu-community-plugins

plugins/springboot/springboot-metrics.rb
Allow to use metrics from Spring Boot based applications. Metrics endpoints, auth and service address can be adjusted.
=> Added a spring boot metrics plugin

plugins/system/check-cpu.sh, plugins/system/check-process.sh
ruby use a lot of cpu power. so when we use several plugins to check the host ,cpu usage become high. Then the cpu usage warning raise by sensu. This is ridiculous. So I wrote some plugins in shell script.
=> renew checks to cpu usage be lower.

plugins/aws/check-rds-events.rb, plugins/aws/check-redshift-events.rb
Also fix a bug in my Redshift check
=> Add plugin to check for critical events on RDS clusters

handlers/notification/clockworksms.rb
Specify the required gem in the clockworksms.rb handler comments.
=> Add requirements to clockworksms.rb handler

plugins/aws/sqs-metrics.rb
it outputs the current message count for a queue
=> add SQS metrics plugin

plugins/redis/check-redis-ping.rb
This is a very simple check for Redis. The other checks already in this repo are great but sometimes it is nice to just do a simple ping/pong check to make sure Redis is alive.
=> Add redis ping check

plugins/mongodb/mongodb-metrics.rb
See http://docs.mongodb.org/manual/reference/server-status/
=> Fix the mongodb server status command.

plugins/system/check-ntp.rb
The check was previously only checking the offset of ntp against the remote server.  However If ntpd is unable to sync with its configured peers it returns an offset of 0 and doesn't trigger the check. 
This modification also checks the stratum, stratum 16 means the device is unsynchronized. http://en.wikipedia.org/wiki/Network_Time_Protocol#Clock_strata
There is the potential for this to generate some false positives as when the ntp service is restarted it can take a bit for it to get synced up with its peers.  
Also added a nice output message that shows the delay.
=> Modified ntp check so it checks the stratum as well as the offset.

plugins/supervisor/check-supervisor-socket.rb
- Fix variable scoping issue.  Variable defined in loop is no longer in
scope outside of it in Ruby 1.9.  Also improve exception handler to
include message.
- Fix processing of result from XML::XMLRPC::Parser.  Whatever data
structure the old code was expecting didn't match reality.
=> Fix check-supervisor-socket.rb

plugins/growthforecast/check-current-value.rb
[GrowthForecast](http://kazeburo.github.io/GrowthForecast/) is RRD graph tool via a WebAPI.
Add plugin(check script), current value in GrowthForecast's graph.
=> Add plugin check current value in GrowthForecast

plugins/nzbget/nzbget-metrics.rb
Connects to the NZBGet API to get its current status.
=> Add plugin for NZBGet metrics

plugins/consul/check-consul.rb
Added consul status and leader check plugin.
=> Added consul status and leader check with plugins/consul/check-consul.rb

plugins/memcached/memcached_socket_graphite.rb
Adding the interfaces speed so % utilization can be graphed in dashboard
=> Add interface speed

handlers/notification/xmpp.json, handlers/notification/xmpp.rb
This PR is actually used on production and works correctly.
=> Adding a password field to join conference protected by password

plugins/security/check-selinux.rb
very simple check to ensure SELinux is enabled/disabled.
=> SELinux check

plugins/mesos/marathon-metrics.rb, plugins/mesos/mesos-metrics.rb
Updates mesos server flag to avoid issues with scheme flags.
=> Update server flags

plugins/jenkins/check-jenkins.rb, plugins/jenkins/healthcheck-jenkins.rb, plugins/jenkins/jenkins-metrics.rb
=> Jenkins check, extended healthcheck and jenkins Metrics

plugins/jenkins/jenkins-jqs-metrics.rb
=> jenkins-jqs plugin metrics harvesting

plugins/smart/check-smart.rb
Passwordless sudo for any command is a REALLY bad idea
=> Advise a more secure sudo setup for check-smart

handlers/notification/pushover.rb
Priorities are set as follow :
Event status                   Pushover priority
-------------------                -------------------------
OK                                  Low (-1)
Warning                          Normal (0)
Critical                            High (1)
Unkown/Other (3+)       Normal (0)
=> Pushover handler - notifications priority

handlers/notification/nexmosms.json, handlers/notification/nexmosms.rb
Based on the twiliosms notification handler , mods to allow usage with nexmo service provider
=> Added nexmo sms service notification

handlers/notification/opsgenie.json, handlers/notification/opsgenie.rb
* allows using the new teams feature
=> add teams param for sending alerts to teams

plugins/zookeeper/check-znode.rb
Check if a zookeeper znode exists and optionally match its contents
=> Check for zookeeper znode and match its value

plugins/ssl/check-ssl-qualys.rb
This check uses the service at https://www.ssllabs.com/ssltest/ and checks that the reported grade is at the specified level.
=> Adds an SSL check from the ssllabs.com API

plugins/cassandra/cassandra-graphite.rb
Collect 'Table:' metrics from 'nodetool cfstats' output.
Before Cassandra 2.0, 'Column Family:' was part of the output.
=> cassandra-graphite.rb: Support Cassandra v2.0 output on cfstats

plugins/system/user-pct-usage-metrics.rb
Gather %mem usage as well as %cpu usage
Add support for outputting uids instead of usernames
=> Improvements to system/user-pct-usage-metrics.rb

plugins/whois/check-whois.rb
A plugin to check domain expiration date with the 'whois' gem
=> Add check-whois.rb

plugins/rabbitmq/check-rabbitmq-consumers.rb, plugins/rabbitmq/check-rabbitmq-messages.rb, plugins/rabbitmq/check-rabbitmq-queue-drain-time.rb, plugins/rabbitmq/rabbitmq-alive.rb, plugins/rabbitmq/rabbitmq-amqp-alive.rb, plugins/rabbitmq/rabbitmq-cluster-health.rb, plugins/rabbitmq/rabbitmq-overview-metrics.rb, plugins/rabbitmq/rabbitmq-queue-metrics.rb, plugins/rabbitmq/rabbitmq-stomp-alive.rb
Also remove old Ruby 1.8.7 compat code
=> Add RabbitMQ Queue Drain Time metric and check

plugins/aws/check-sqs-messages.rb
setting region broke in 28a46b0.
=> get region param working again

extensions/checks/check_graphite.rb, spec/extensions/checks/check_graphite_spec.rb
Converted https://github.com/sensu/sensu-community-plugins/blob/master/plugins/graphite/check-data.rb to sensu extension.
functionality is unchanged.
=> Converted graphite check-data.rb to sensu extension

extensions/checks/haproxy.rb, spec/extensions/checks/haproxy_spec.rb
Converted community plugin check_haproxy.rb to extension format
https://github.com/sensu/sensu-community-plugins/blob/master/plugins/haproxy/check-haproxy.rb
Functionality is unchanged
Added usage example in the comments.
REQUIRES SENSU 0.17.1 OR HIGHER
=> Haproxy Extension Check

plugins/aws/autoscaling-instance-count-metrics.rb, plugins/aws/check-autoscaling-cpucredits.rb
Hi,
This is a first attempt at writing some Ruby so please be gentle. (Why's cartoon foxes are helping me to understand more... )
It passes rubocop with an inherited yellow tech debt exception because I simply don't know enough Ruby to solve the problem cleanly.
The code works for me :)
Cheers,
Gavin.
=> AWS AutoScaling group check for low CPU credits on t2 instance types

plugins/rabbitmq/check-rabbitmq-queue.rb
Thanks @edennis-sge
Time to write some specs!
=> Skip should be next in check-rabbitmq-queue

plugins/system/check-ram.rb
Updated check-ram.rb to work with the new version of free from procps-ng version 3.3.10
=> Updated check-ram.rb to work with the new version of free 

plugins/http/http-json-graphite.rb, sensu-plugins.gemspec, spec/fixtures/plugins/http/input.json, spec/plugins/http/http-json-graphite_spec.rb
This is a plugin that hits an HTTP endpoint which emits JSON and pushes data into Graphite. It is currently not extremely feature rich, but is meant to be generic and hopefully extendable.
Any feedback would be welcome.
=> Adding http-json-graphite.rb with test

plugins/rabbitmq/rabbitmq-overview-metrics.rb
Add "Global Counts" as seen in RabbitMQ mgmt web UI
=> Add global counts metrics

handlers/other/ec2_node.rb
=> Changed authentication to use IAM roles instead of keys.

plugins/mongodb/mongodb-metrics.rb
=> ported to work with mongo driver 2.X

plugins/mesos/check-marathon.rb, plugins/mesos/check-mesos.rb, plugins/mesos/marathon-metrics.rb, plugins/mesos/mesos-metrics.rb
Add `-t`, `--timeout` option in case default 5 seconds is too short.
=> add timeout option to mesos checks
