sensu/sensu-community-plugins

plugins/gpg/check-gpg-expiration.rb

A Ruby Sensu script to check how many days are left before a given GPG key is
about to expire. The script should run on all any unix variant, aslong
as GPG is installed. Currently path to GPG is hardcoded to /usr/bin/gpg.
Yasser

Add GPG Key expiration check

---

CONTRIBUTING.md
README.md
Rakefile

While keeping the standard use case of one userkey / token key pair, the pushover notification handler can now also send a single event to multiple userkey / token pairs configured in the sensu pushover config file.

Send pushover notification to multiple userkey / token pairs.

---

plugins/logging/check-log.rb

Defaults to false, so functionality unchanged if not set.
Returns the first 250 characters of the matched line.

check-log, new option -r, returns matched line.

---

plugins/ipmi/check-sensor.rb

This plugin allows you to check IPMI sensors, usually for temperature data.  It returns a graphite formatted response.

Sensu Plugin For Checking IPMI Sensors (e.g. temperature)

---

plugins/ceph/check-ceph.rb
plugins/cucumber/check-cucumber.rb
plugins/java/java-permgen.rb
plugins/processes/check-cmd.rb
plugins/raid/check-megaraid_sas-status.rb
plugins/system/check-process-restart.rb

$? works without require English however, CHILD_STATUS needs it and throws an exception unless it is specifically required. Rubocop suggests using CHILD_STATUS over $?. Similar issue is detailed here: https://github.com/bbatsov/rubocop/issues/854
Either we should require English in all relevant plugins or, we should revert back to $?.
This can be tested as follows in test.rb:
```
stdout = `ls -ltr`
puts ($CHILD_STATUS.exitstatus.to_s)
```
gives:
```
test.rb:4:in `<main>': undefined method `exitstatus' for nil:NilClass (NoMethodError)
```
Adding ``` Require 'English' ``` gives:
```
ruby test.rb
0
```
Also has the same behaviour as require English if you add replace CHILD_STATUS with $?

Bugfix: All plugins using CHILD_STATUS require 'English'

---

handlers/remediation/sensu.rb

Using `$LAST_MATCH_INFO` without requiring the English lib returns nil.
Somewhat related with #945 :smile:

Require 'English' for $LAST_MATCH_INFO

---

plugins/system/check-memory-pcnt.sh

Modified the comments at the top of the check-memory-pcnt.sh plugin to state the requirement of bc.
bc is not installed on a default CentOS 6.5 server and without it this check fails with unknown (exit code 3).

Add requirements list to check-memory-pcnt.sh

---

handlers/notification/clockworksms.json
handlers/notification/clockworksms.rb

Allow specifying who the SMS is sent from.  Backwards compatible and defaults to "SENSU" if not specified.

Clockwork sms "from" field

---

handlers/notification/slack.json
handlers/notification/slack.rb

Don't send slack handler now.
because, changed slack webhook url format. 
this PR is supported new format.

Fix slack handler

---

extensions/checks/system_profile.rb
extensions/checks/wmi_metrics.rb
plugins/elasticsearch/es-node-graphite.rb
plugins/rabbitmq/rabbitmq-node-health.rb
plugins/windows/check-service-windows.rb
plugins/windows/check-windows-cpu-load.rb
plugins/windows/iis-current-connections-metrics.rb
plugins/windows/iis-get-requests-metrics.rb

For the windows wmi_metrics.rb the option was added to put the graphite prefix at the start - default mode is old mode of postfixing the metric name with the prefix.
Added new plugin for checking the health of a RabbitMQ server

Fixes and updates for windows checks - new plugin rabbit-mq-node-health.rb

---

plugins/system/cpu-metrics.rb

RHEL kernels don't have cpu.guest metric

Fixed issue with RHEL-based kernels.

---

plugins/system/user-pct-usage-metrics.rb

We have a shared box and would like to track the percentage CPU used by each user, including all processes owned by a user. The backticked ps command is tested on Linux, OS X and FreeBSD.

Report CPU usage by user

---

plugins/graylog2/check-graylog2-alive.rb

New check based on the rabbitmq-alive check to test whether the graylog2-server is up and running correctly.

Add check for graylog2 aliveness

---

plugins/system/check-process.sh

The `$0` variable refers to the current script with full path. But if the plugin registered without the full path, then it is not properly filtered out. This causes it to report stopped processes as running.

Fixed bug in check-process.sh

---

handlers/notification/mailer.rb

Could not find 'mail' (~> 2.5.4) - did find: [mail-2.6.3] (Gem::LoadError)

Removed mail gem version constraint

---

plugins/icecast2/check-icecast2-alive.rb
plugins/icecast2/icecast2-metrics.rb

Adds a basic is server alive check and a metrics plugin to pull stats for the server and all registered mount points.

Add Icecast2 alive check and metrics plugins

---

plugins/ssl/check-ssl-host.rb

Connects to a HTTPS (or other SSL) server and performs several checks on the certificate:
- Is the hostname valid for the host we're requesting
- If any certificate chain is presented, is it valid (i.e. is each certificate signed by the next)
- Is the certificate about to expire
There are a couple of other plugins that work with SSL certificate, but other plugins focus mostly on expiry, and don't support SNI (except for the net/http based ones in ruby 2.0 and above).

check-ssl-host plugin

---

plugins/aws/check-rds.rb

Add sane defaults
Warn the user when they don't provide and instance type
Support Amazon's T2 instance types
Return a smaller message that will work better with text message alerts
Handle time periods in Cloudwatch that are smaller than the default in the check instead of throwing Ruby errors

Improvements to check_rds.rb

---

plugins/system/disk-usage-metrics.rb

Adds an option to filter disk types via df -t <type>, useful when running on Cumulus Linux to avoid df crapping out on /cumulus/switchd

Add df disk type filter option

---

plugins/kannel/check-kannel.rb

It is a simple plugin for Kannel to check if all SMSC connections are online.
We are currently using this plugin to monitor our Kannel instance. It is possible to add a few more features/options, but this is a good starting point that fitted our needs. :)

Plugin to check Kannel SMSC connections

---

plugins/system/interface-metrics.rb

This is needed when interface names contains dot like: eth2.99 as the info is wrongly stored in graphite.

replace dots in interfaces' name for _

---

plugins/aws/check-redshift-events.rb

Also add usage information and refactor the large amount of code in the run method into individual methods
As an added bonus if the cluster goes away you'll get an alert now since passed in clusters are now checked against those in the region

Add the ability to only monitor certain redshift clusters

---

handlers/notification/mailer.rb

The mailer handler sends entire command lines via mail. Often command lines contain passwords which might then be send through the internet in plain text.
The PR tries to redact simple passwords.

Redact passwords from output and command via mailer notification handler

---

extensions/checks/system_profile.rb

The "\" character is not needed for the array construction. Using this result in an array like the following.
```
["rxBytes", "\nrxPackets", "\nrxErrors", "\nrxDrops", "\nrxFifo", "\nrxFrame", "\nrxCompressed", "\nrxMulticast", "\ntxBytes", "\ntxPackets", "\ntxErrors", "\ntxDrops", "\ntxFifo", "\ntxColls", "\ntxCarrier", "\ntxCompressed"]
```

Fixed system_profile net metrics array creation

---

plugins/gpg/check-gpg-expiration.rb

In most cases the sensu client will be as a different user to the one that owns the
GPG home directory and will not have write permissions to the home
directory. As we are only reading keys, we don't need (or want) to
create a lock file. This means we can give read permission to the GPG
homedir without giving write permission.
In future, it might be worth considering adding an option for the user
and using sudo to run the command.
Yasser

Do not create lock for GPG key check

---

handlers/notification/slack.json
handlers/notification/slack.rb

* Support multiple configurations, following: https://github.com/sensu/sensu-plugin/issues/66
* Revert deletion of channel setting. It is still possible to override the default channel: https://api.slack.com/incoming-webhooks

Allow multiple slack configurations

---

plugins/system/check-smart.rb

Our use case : DRBD volumes that appear as disks and are not considered as smart-incapable. They produce unwanted noise in the output.

check-smart.rb: allow to exclude disks by name pattern

---

plugins/gpg/check-gpg-expiration.rb

Numerical comparison fails, so forcing to integer.
Yasser

Force warn and crit string to int

---

plugins/system/check-mem.sh

The free utility provided with F21 doesn't print the buffers/cache line. The Mem line contains all the needed memory info.

Added FREE_MEMORY condition for Fedora 21

---

plugins/rabbitmq/check-rabbitmq-queue.rb

If RMQ queue is new and never had messages, then it will return
null in place of message count and plugin crashes. This fix will return
0 if queue wasn’t used.

Fix: returns 0 if RMQ queue is new

---

plugins/http/check-http.rb

The change adds the following support to the check http script.
1) Specify a custom proxy url using the newly introduced "--proxy-url <proxy_url>" option.
2) Choose to not pick the environment http_proxy variable in certain scenarios using the newly introduced "--noproxy" flag.
3) Create an HTTP connection with default env proxy settings if the above 2 are not satisfied.
Specifying a custom proxy host and a proxy port during the Net:HTTP object initialization allows to override the environment http_proxy variable. The Net:HTTP library does not support reading of the "no_proxy" environment variable. However the behavior can be achieved where the request should not go through the proxy server using nil values explicitly specified for proxy_host and proxy_port in the Net:HTTP object …

Added custom proxy + no proxy support to check http

---

plugins/network/check-banner.rb

`check-banner.rb` plugin cause the folloing error because of invalid shebang.
```
sudo /etc/sensu/plugins/check-banner.rb
/etc/sensu/plugins/check-banner.rb: 14: /etc/sensu/plugins/check-banner.rb: cannot open 1.9.0: No such file
/etc/sensu/plugins/check-banner.rb: 14: /etc/sensu/plugins/check-banner.rb: require: not found
/etc/sensu/plugins/check-banner.rb: 15: /etc/sensu/plugins/check-banner.rb: require: not found
/etc/sensu/plugins/check-banner.rb: 16: /etc/sensu/plugins/check-banner.rb: require: not found
/etc/sensu/plugins/check-banner.rb: 17: /etc/sensu/plugins/check-banner.rb: require: not found
/etc/sensu/plugins/check-banner.rb: 19: /etc/sensu/plugins/check-banner.rb: cannot open Sensu::Plugin::Check::CLI: No such file
/etc/sensu/plugins/check-banner.rb: 19: …
```

Fix invalid shebang

---

handlers/metrics/elasticsearch_metrics.json
handlers/metrics/elasticsearch_metrics.rb

I added Elasticsearch metrics plugin and setting file.
Its original repository is [hico-horiuchi/sensu-elasticsearch](https://github.com/hico-horiuchi/sensu-elasticsearch).
It is forked from [inokappa/sensu-handler-metrics-elasticsearch](https://github.com/inokappa/sensu-handler-metrics-elasticsearch).

Add Elasticsearch metrics handler

---

plugins/system/iostat-extended-metrics.rb

On a typical iostat output like this.
```
Linux 2.6.32-358.23.2.el6.x86_64         02/11/2015      _x86_64_        (8 CPU)
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
6.03    0.03    4.70    0.43    0.00   88.81
Device:         rrqm/s   wrqm/s     r/s     w/s   rsec/s   wsec/s avgrq-sz avgqu-sz   await  svctm  %util
sda               0.05    31.17    0.47   10.51    36.31   323.95    32.80     0.04    3.30   0.78   0.86
sdb               1.23   245.51    6.43   29.94  1751.01  2203.62   108.74     0.13    3.47   0.82   2.99
sdc               0.34    15.82    1.59    0.65    33.67   131.82    73.94     0.84  377.24   3.01   0.67
```
The avg-cpu information would be given the wrong header, each one shifted to the left. e.g. steal being given the value for idle.

Fixed iostat-extended-metrics giving the wrong header for values.

---

handlers/notification/pagerduty.rb

This can be used to specify environment (e.g. prod vs QA).

Add incident_key_prefix and description_prefix to PagerDuty handler.

---

handlers/metrics/influxdb-metrics.rb

I had an issue where `@event['check']['output']` was a string value.  I don't know if this is always the case, or just for the `cpu_usage` metric I am trying out, but coercing it to be an array fixed the issue for me.  This should have no effect if the metrics are already an array.

Ensure the metrics come in as an array

---

handlers/notification/ponymailer.rb

The error results in an `undefined e! method` due to the space between __merg__ and __e!__.

Fixes simple whitespace error.

---

extensions/checks/system_profile.rb

This is actually a bug which manifests in adding newlines to the array
which adds metrics with an empty name.

Removes unnecessary newline escapes.

---

handlers/notification/graphite_event.rb

Use the Output from the check as the content of the data field for the event,
and use the timestamp from the check itself rather than the time the handler
runs - this accounts for delay in executing the handler due to latency, or
rabbitmq message processing.

Improve graphite-event data and timestamp

---

handlers/notification/graphite_event.rb

Should probably use Net::HTTPS, but this allows for users to have non-ssl enabled Graphite installations and for the graphite_events to dynamically recognise the protocol to use.

Only use SSL if the graphite uri is https

---

handlers/notification/ponymailer.rb

Before removing the arguments option I would get undefined method
arguments for the Mail::Message object.
I'm using the pony gem version 1.11 and mail gem version 2.6.3.

Removes the unused arguments option which results in an error.

---

handlers/notification/slack.rb

I used this handler and encountered two errors:
- the check notification was not put into the description as designed
- the post body was not being sent as json, and thus had issues with sending urls and other text.
This PR corrects both issues. :smile_cat:

correct path to notification element & correct post format

---

mutators/officehours.rb

1) Remove require ruby gems since all plugins have removed hash rockets thus eliminated Ruby 1.8.7 support already
2) Factor out some of the logic into methods to make things easier to read
3) Add support for GMT offsets.  Most servers run in GMT while most offices are not in GMT.  This mutator was really checking if it was office hours where the server was before.  Now you can modify the mutator for you local offset (ex PST is -08:00)
4) The mutator now adds office_hours = false to the event JSON not just office_hours = true.  This gives more useful information for consumption by downstream handlers

Improvements to the office hours mutator

---

handlers/notification/slack.json
handlers/notification/slack.rb

1) strip the newline off sensu command output that lead to odd formatting
2) Enable markdown by default, but add a new config option markdown_enabled that allows you turn it off if you have markdown like text strings coming back (there's no escape characters for slack markdown)
3) Added bolded headers of "check" and "description"
Old:
New

Improve the formatting of slack notices

---

plugins/aws/autoscaling-instance-count-metrics.rb
plugins/aws/check-dynamodb-capacity.rb
plugins/aws/check-dynamodb-throttle.rb
plugins/aws/check-ec2-network.rb
plugins/aws/check-elb-certs.rb
plugins/aws/check-elb-health-sdk.rb
plugins/aws/check-elb-latency.rb
plugins/aws/check-elb-nodes.rb
plugins/aws/check-elb-sum-requests.rb
plugins/aws/check-instance-events.rb
plugins/aws/check-rds-events.rb
plugins/aws/check-rds.rb
plugins/aws/check-redshift-events.rb
plugins/aws/check-ses-limit.rb
plugins/aws/check-sqs-messages.rb
plugins/aws/ec2-count-metrics.rb
plugins/aws/elasticache-metrics.rb
plugins/aws/elb-full-metrics.rb
plugins/aws/elb-metrics.rb
plugins/aws/sqs-metrics.rb

Due to the breaking release of v2 of the aws-sdk gem all of the current plugins need to be set to require aws-sdk-v1

Set all aws plugins to depend on aws-sdk-v1 that currently use the aws-sdk gem

---

plugins/aws/check-instance-events.rb

The logic in https://github.com/sensu/sensu-community-plugins/commit/04106ed83ef769470512e3a1dd2d56e1b772f957 was flawed and it causes this check to never return any instances with events.  Instances are being excluded if the select finds a reboot completed, but an empty array satisfies the unless so it never finds any instances even if they events.  I've tested this change in logic in my environment to show the nodes Amazon is about to reboot.  This should get merged ASAP since the event is upcoming for everyone.

Fix broken instance event check

---

plugins/system/process-uptime-metrics.sh

Although there was a pre-existing plugin for checking whether a process is running or not, there was no plugin to track the uptime of a process over a prolonged interval of time. This newly written plugin uses the same logic which was used to check whether the process is running or not, with an addition that it instead echoes a metric with a value of 1 or 0 depending on the running state of the process, in graphite plaintext metric format i.e." metric_name metric_value timestamp"

New plugin to generate process uptime metrics

---

plugins/system/package-updates-metric.py

package-updates-metric is used to check available package updates for Debian or Ubuntu system.
`package-updates-metric.py` can get a list of available package updates. Each record in the list includes:
* Package name
* Flag security?
* Current version
* Candidate version
The script has 4 exit statuses:
* OK(0): No available updates
* WARNING(1): Normal updates are available
* CRITICAL(2): Security updates are available
* UNKNOWN(3): Errors or exceptions
The script dumps the list to JSON and outputs JSON-formatted text to stdout. The output can be parsed in mutator or handler.

Add package-updates-metric.py

---

handlers/notification/slack.json
handlers/notification/slack.rb

Using a http proxy like squid is common enough that it should be as easy to use as setting the proxy ip and port in your json config for the slack handler.
This does that.

updated slack.rb to use http proxy if defined

---

plugins/system/check-btrfs.rb

I am not the original author but have made some changes to conform to some standard practices in ruby 1.9.1
This was verified in a docker container running the sensu client. The host was coreos which has / as btrfs.
Output in different scenarios:
failure to run get proper btrfs data:
root@9b4ef9db387f:/etc/sensu# ./plugins/aio/check-btrfs.rb
sudo: btrfs: command not found
CheckBtrfs UNKNOWN: No devices found
Run plugin with no options (provided) accepting all defaults and having status "ok":
root@9b4ef9db387f:/etc/sensu# ./plugins/aio/check-btrfs.rb
CheckBtrfs OK: All devices usage under 85%
Run plugin with options that will have a status "warning":
root@9b4ef9db387f:/etc/sensu# ./plugins/aio/check-btrfs.rb -w 10 -c 90
CheckBtrfs WARNING: /dev/xvda9 28.75%
Run plugin with options that …

adding a check for btrfs disk space. 

---

extensions/checks/wmi_metrics.rb

The current `wmi_metrics.rb` extension check polls every 10sec by default, resulting in 6 1sec datapoints. This means you have values for those 6 seconds spread across the minute, instead of an accumulative value for the whole minute.
These changes total the network traffic datapoints over 60 seconds, polling every 1sec with a periodic timer. All other metrics are polled once every 60 seconds.

Windows WMI metrics accumulate network data over interval

---

plugins/snmp/snmp-bulk-metrics.rb
plugins/snmp/snmp-metrics.rb

Add custom MIB loading capabilities to provide better metric names in output.
Rescue cases where a failure to float a value may occur.

snmp metrics improvements/fixes

---

plugins/nginx/nginx-metrics.rb

Bugfix - nginx-metrics.rb: Creates 10 GET requests because didn't check the status code

---

handlers/notification/pagerduty.rb

This allows you to have multiple pager duty handlers that use different sets of API keys, incident prefixes, etc.  Much more powerful that using the team functionality, which only allows for multiple keys.

Allow specifying a custom JSON block name in the pager duty handler

---

plugins/golang/golang-stats-api-metrics.rb

Adding plugin to collect golang application status (CPU, memory, GC, etc.) via golang-stats-api-metrics.
https://github.com/fukata/golang-stats-api-handler

Add golang-stats-api-metrics

---

plugins/mongodb/mongodb-metrics.rb

The plugin failed to connect to a MongoDB server that only allows SSL connections.
I've patched it with SSL mode options (by default disabled).

Update mongodb-metrics.rb to add SSL mode

---

.rubocop.yml
plugins/network/check-banner.rb

Some TCP checks doesn't have a banner information such as statsd or other custom app.

Enable TCP Check with no banner.

---

plugins/http/check-https-cert.rb

Not sure if message is a relic of the past or something, but as I was testing this check, I wasn't getting any output, so I made it call unknown anyway and now it works great.

Use unknown instead of message

---

plugins/elasticsearch/es-node-graphite.rb

Hello,
we need to track more metrics from ES servers(size of fielddata and filter_cache) and these were limited by  ```/(_time|memory|size$)/``` regular expression. New approach is to test the value and add when it's numerical. Previous ```/_time/``` is kept for some backward compatibility with older version of ES (and maybe it's not needed).

ES graphite node - return more metrics

---

plugins/cassandra/cassandra-graphite.rb

We can now run cassandra-graphite.rb with -u/-p options for those using
authentication on the JMX.This is best practice considering the new recent
vulnerability affecting Cassandra:
CVE-2015-0225 ( http://www.securityfocus.com/archive/1/535154 )

Added username/password support for nodetool - cassandra-graphite.rb - Cassandra monitoring

---

plugins/system/check-disk-health.sh

Some firmware reports
=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK
on `smartctl -H`.
http://sourceforge.net/p/smartmontools/mailman/message/32936537/

Fix check-disk-health for OK status

---

plugins/rabbitmq/rabbitmq-node-health.rb

In our rabbit nodes, we sometimes have issues with running out of sockets or file descriptors. Updating file to accommodate those checks. I also noticed a warning about rest_client being deprecated, so I swapped it to rest-client.
Apologies for any sloppiness. Ruby is not my forte'.

more checks to rabbitmq-node-health.rb

---

handlers/notification/statuspage.rb

I added support for updating a component if defined for the StatusPage.io handler. Tested this out in our environment and it works well. If there are necessary changes to get this merged let me know, Ruby is not my native language. 
(gem install redphone does not provide a gem with StatusPage.io support so I've also added instructions on how to get that working)

Added component support to StatusPage.io handler

---

plugins/rabbitmq/check-rabbitmq-consumers.rb
plugins/rabbitmq/check-rabbitmq-messages.rb
plugins/rabbitmq/check-rabbitmq-queue-drain-time.rb
plugins/rabbitmq/check-rabbitmq-queue.rb
plugins/rabbitmq/rabbitmq-alive.rb
plugins/rabbitmq/rabbitmq-amqp-alive.rb
plugins/rabbitmq/rabbitmq-cluster-health.rb
plugins/rabbitmq/rabbitmq-network-partitions.rb
plugins/rabbitmq/rabbitmq-node-health.rb
plugins/rabbitmq/rabbitmq-overview-metrics.rb
plugins/rabbitmq/rabbitmq-queue-metrics.rb
plugins/rabbitmq/rabbitmq-stomp-alive.rb

Standardize headers.  Add dependency / platform information
Resolve rubocop warnings
Remove Ruby 1.8.7 backwards compat
Also brings in additional metrics for the queue monitor (egress rate and consumer count)

Sync changes from sensu-plugins-rabbitmq repo

---

plugins/aws/elb-full-metrics.rb

Run:
./elb-full-metrics.rb -n ELBName -r Region -s AWS
Error:
Error: exception: The parameter Statistics.member.1 must be a value in the set [ Sum, Maximum, Minimum, SampleCount, Average ].

Value for SurgeQueueLength in statistic_type Fixed

---

plugins/system/conntrack-metrics.rb

This keeps warning messages from being sent to graphite in addition to the metric values.

Exclude errors in the conntrack shell output

---

plugins/sidekiq/check-sidekiq.rb
plugins/sidekiq/sidekiq-metrics.rb

We use these scripts to monitor and gather stats from [sidekiq](https://github.com/mperham/sidekiq). They can load data from a [sidekiq-monitor-stats](https://github.com/harvesthq/sidekiq-monitor-stats) enabled endpoint. One just needs to install that gem in the running rails app and the endpoint is available. 
We're very happy with this solution because it warns us when things stop working or our sidekiq workers can't deal with the load, while being flexible enough to allow for some wiggle room (during deploys or other situations that aren't really critical). The metrics we gather let us very clearly see if and when we're going to need more capacity. 
I'll update that gem's README if this is merged.
Let me know if there's anything I need to update. I tried to follow the guidelines, …

Sidekiq stats and check scripts

---

plugins/files/check_dir_count.rb
spec/plugins/files/check_dir_count_spec.rb

- Adding a new option for the check dir count plugin so that we can specify the file patten that we would like to count. This is not mandatory and default to '*' so that it is backward compatible. 
- Rspec test are include to make sure the new option is backward compatible. 
- minor code change was made so that the unknown status can be detect in the rspec test

Additional pattern option for check dir count

---

plugins/http/check-http-json.rb
sensu-plugins.gemspec
spec/plugins/http/check_json_spec.rb

- Added a spec for http-json-check.
- This requires webmock for dev dependency (gemspec file).
- Run the test with:
`$ bundle install; bundle exec rspec spec/plugins/http/check_json_spec.rb`
- Ran the script manually with ruby/like the example, worked fine.
- Added example documentation with single key, as was before.
- Added example documentation with nested key form.

Added support for nested keys in http-json-check

---

plugins/system/vmstat-metrics.rb

Almost all distros are already showing steal cpu.
I added it. In case of a system without steal cpu information it would be 0.

Adding steal at the cpu metric

---

plugins/files/check-mtime.rb
plugins/smart/smart.json

The gem was in reference to the fileutils require, which built into ruby so there's no gem to specify there.

Remove an extra space and remove a ? for a gem

---

plugins/rabbitmq/check-rabbitmq-consumers.rb
plugins/rabbitmq/check-rabbitmq-messages.rb
plugins/rabbitmq/rabbitmq-queue-metrics.rb

Avoid incredibly small egress numbers breaking graphite output
Allow monitoring all queues except those you exclude in the consumer count check
Allow specifying per queue message count thresholds vs. system level message count thresholds

Sync RabbitMQ changes from the rabbitmq sensu plugin repo

---

plugins/system/check-mem.sh

* add regexp to be able to match fedora (> 20)or rhel (> 7.0), without
this patch, if not possible to use this plugins on rhel

fix redhat-version for fedora and rhel for check-mem.sh

---

.gitignore
plugins/http/check-http.rb

This PR is a proposition of two changes:
- Add the ```-w``` or ```--whole-response``` to the ```check-http.rb``` check. When the check is failing, the whole message received will be displayed in the message
- Add the intellij project files to ignored in gitignore.

Add ability to print whole response in check-http

---

plugins/processes/check-procs.rb

Check for processes NOT owned by user
e.g.
```
CheckProcs OK: Found 6 matching processes; cmd //var/lib/dmcm/etc/; not user root
dmcmsvc  /usr/lib/jvm/java-7
-Dfile.encoding=UTF-8 -Duser.timezone=UTC -Djava.net.preferIPv4Stack=true ...  -Ddcm.configurationSource.localURL=file:///var/lib/dmcm/etc/dcm-config-local.yaml
...[ 6 more similar processes ] ...
```

Added user-not flag

---

plugins/files/check-file-size.rb
spec/plugins/files/check-file-size_spec.rb

Add a check that allows Sensu to check for a file size (warn and critical sizes). Also allows to not go critical if the file just doesn't exist.
USAGE:
check-file-size.rb -f <file> [optional parameters]
-c, --critical SIZE              The size (in bytes) of the file where CRITICAL is raised, default of 3,000,000
-d, --debug                      Output list of included filesystems
-f, --file FILENAME              file to stat (full path) (required)
-i, --ignore-missing             Do not throw CRITICAL if the file is missing
-w, --warn SIZE                  The size (in bytes) of the file where WARNING is raised, default of 2,000,000
EXAMPLES:
WARN if file is over 15,000 bytes:
```
check-file-size.rb -f ./test-file -w 15000
CheckFileSize WARNING: ./test-file is greater than 15,000 bytes! …
```

Add check-file-size.rb Files plugin

---

plugins/openstack/keystone/check_keystone-api.sh

In Enterprise production environments, having this check fail after 10 seconds (as was hard-coded into script) can lead to an unnecessary flood of alerts. Failing to get a token in less than 10 seconds does not necessarily indicate an issue. I have tested increasing the timeout to 15 seconds, and that seems to be a good value for our environment. Whatever the correct value will be for a given environment, it is much better to pass the value as an option rather than having it hard-coded into the script.

add TIMEOUT option so token timeout value is not hardcoded
